### ISSUE TITLE
Separate email and password screens for login

### ISSUE THREAD

**Issue by okdistribute** [deltachat/interface#1]
The password input can be confusing for new users, and will change depending on what email address (domain) they're using. For example, gmail requires you use a separate access code rather than your password. So the clients should offer some suggestions in the UI based on the email address that was entered.

This is also a technique used by slack on signing up

**Comment by Jikstra** [comment]
![login_bubble_thing](https://user-images.githubusercontent.com/34889164/47659452-4fc94280-db95-11e8-85f0-98fb082f0119.png)

I think this bubble point click through thing could suit very well our needs for the different screens.

**Comment by r10s** [comment]
i think this will be targeted by the upcoming provider-info.
