### ISSUE TITLE
unique emojis

### ISSUE THREAD

**Issue by r10s** [deltachat/interface#12]
desktop has moved to the google emojis, so they are no longer exactly the same as on android, https://github.com/deltachat/deltachat-desktop/issues/483

at a given point, we should figure out the details and check which emojis we want to use.

**Comment by Simon-Laux** [comment]
#13 
Also I would suggest looking for an artist and creating **our own emoji set** in the long run.

Other options would be the currently available opensource emoji fonts like emojione or google noto.

**Comment by karissa** [comment]
I think creating our own emoji set seems out of scope, unless someone really wants to volunteer that time to do it!
there must be some open source small emoji set that exists for this purpose

**Comment by Simon-Laux** [comment]
Everything that is a font is fine with me. I have no special preferences on emoji style, but @dignifiedquire for example dislikes emojione and noto.

**Comment by ralphtheninja** [comment]
It would obviously be totally awesome with our own emoji set but it doesn't feel like a realistic goal. I'd personally prefer to pick something with an open license, e.g. emojione.

**Comment by dignifiedquire** [comment]
emojione is not fully opensource if you look at the licenses here: https://www.emojione.com/

**Comment by r10s** [comment]
this issue is a bit stale. maybe meanwhile this is not really a big issue. browsing through https://emojipedia.org , things are quite similar on newer platforms.

also, we use the system-emoji picker eg. on ios, this would add some additional problems when forcing a different icon set.

closing this issue for now. feel free to re-open if you think this is still an issue.
