### ISSUE TITLE
emojis licensing/copyright

### ISSUE THREAD

**Issue by Jikstra** [deltachat/interface#13]
@Simon-Laux had some interesting/important thoughts about the legal status of the emojis we're currently using. Maybe he can reevaluate it a bit?

The gist was that it's maybe not fine for us to use the apple emojis which are a subset of the emojis we currently have on android.

**Comment by Simon-Laux** [comment]
As I discussed which emoji pack we should use with @dignifiedquire on IRC, because I want to use fonts instead of Images for emojis, we found out that apple wants to restrict the usage of its emoji font - https://blog.emojipedia.org/apples-emoji-crackdown/
