### ISSUE TITLE
Delta Chat, DeltaChat, Delta.Chat, Delta.chat, delta.chat, Delta, ...

### ISSUE THREAD

**Issue by r10s** [deltachat/interface#16]
during review of the website and of the app, moni and me encounter a lot of different spellings for the app name.

esp. on the same website, we should avoid different spellings, however, it would be good to have a common agreement on this.

in german, the spelling with the space gets unhandy wrt compound words as "Delta Chat-Probleme" - normally, one would have to write it as "Delta-Chat-Probleme" which however would introduce another spelling, "Delta-Chat". from this side, "Delta.Chat" is easier. however, i'm pretty sure, other languages will have their own pitfalls on this issue ...

**Comment by angelo-fuchs** [comment]
I'm all for dieversity.

**Comment by violoncelloCH** [comment]
@angelo-fuchs of course, that's true!

**Comment by r10s** [comment]
@angelo-fuchs that's a good point!

**Comment by r10s** [comment]
so maybe, it's just fine if it is consistent at least within a webpage or so.

**Comment by hpk42** [comment]
FWIW i am moving towards "Delta Chat" in most places, and then "Delta/Android", "Delta/Desktop" if it's clear that this is about Delta Chat.

**Comment by hpk42** [comment]
k, let's consider this resolved ;)
