### ISSUE TITLE
Adaptive icon

### ISSUE THREAD

**Issue by gitlerat** [deltachat/interface#19]
Hi, 
i want to make an adaptive icon for deltachat, but I need to know which font is used for the delta symbol on the launcher icon.

additional infos:
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive

**Comment by Simon-Laux** [comment]
@gitlerat can you post it on @violoncelloCH's forum topic? And then @violoncelloCH can add it to the poll?

I personaly like that logo, but it fits better into an icon pack of that syle than as main icon in my opinion.
