### ISSUE TITLE
login instructions

### ISSUE THREAD

**Issue by kermoshina** [deltachat/interface#22]
As the UX tests have shown, users feel uncomfortable with giving their "real e-mail passwords". I suggest we give a better explanation of how Delta Chat is treating passwords. Currently the app says "There are no Delta Chat servers, your data stays on your device!" 

We can replace it by "There are no Delta Chat servers, your password stays on your device" or "Delta Chat does not store your login information on a server, your data stays on your device".

**Comment by r10s** [comment]
closing stale issue

the current state is pretty close to the suggestion of @kermoshina ...

> We can replace it by "There are no Delta Chat servers, your password stays on your device" or "Delta Chat does not store your login information on a server, your data stays on your device".

... i assume it was changed by that suggestion, but it was forgotten to close this issue :)
