### ISSUE TITLE
login button

### ISSUE THREAD

**Issue by kermoshina** [deltachat/interface#23]
Currently the login button is located in the upper right corner, and users have complained that it is not very visible. Other popular applications have a dedicated "Login" or "Connect" button.

It may be better to locate the "Login" button in the central lower part of the screen, under "Advanced settings". Something like this: 
![photo_2019-09-13_13-53-08](https://user-images.githubusercontent.com/16879492/64860570-d8c25e80-d62d-11e9-9424-7e6eb5983477.jpg)

**Comment by r10s** [comment]
wrt login-button position: there is also the issue that the button is covered by the keyboard. in fact, we had it at the suggested place at some point and ppl just do not see it. 

so, i think, these "on lower half of screen buttons" do only work out well if there is no text to enter on the view.

**Comment by r10s** [comment]
closing stale issue, there are not many reports these days that the "log in" or "ok" button is not found, also, there is a new "welcome screen" before the dialog meanwhile, so the things are not really comparable anyways

also, the mentioned issue with the keyboard covering buttons is pretty valid on mobile

also, we'll probably revamp the onboarding for 1.44 anyways, which would require another user testing
