### ISSUE TITLE
Rename 'Me' to 'Saved Messages' with own icon and make it more prominent

### ISSUE THREAD

**Issue by Jikstra** [deltachat/interface#26]

**Comment by r10s** [comment]
@Jikstra why exactly do you want the rename to happen? mainly to be similar to telegram?

i want to note that we do not really "save" messages to the "Me" chat but forward them there.

so, the sender is always "Me", the original sender is dropped and messages appear on the right.

this behavior may not match the expectation for a chat that is named "saved messages" - but "Me" seems to be fine.

so, i think, we can show the chat by default, however, a simple rename may not be sufficient to get the functionality of "saved messages"
