### ISSUE TITLE
Warn when importing a backup from a newer db version

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/interface#27]
I believe we should warn users when importing a backup with a db version thats newer than the max supported db version.
Something along the lines:
```
This Backup was created from a newer Version of delta chat
and is likely to be incompatible.
Proceed?
(If you can update DC we recommend you to do that BEFORE importing this backup.)
```

What do you think?
CC @hpk42 @r10s @link2xt

**Comment by r10s** [comment]
do you know situations, where this is a real issue?

**Comment by Simon-Laux** [comment]
Without a warning we can get more folks that report difficult to reproduce issues, linked to a broken database in this way.

**Comment by r10s** [comment]
hm, i think most issues with broken databases follow the normal increase-version-path - with maybe broken development versions in between. this won't be catched by such a warning.

**Comment by Simon-Laux** [comment]
now tracked in deltachat/deltachat-core-rust#2294

**Comment by Simon-Laux** [comment]
> hm, i think most issues with broken databases follow the normal increase-version-path - with maybe broken development versions in between. this won't be catched by such a warning.

multidevice with one app more updated than the other is the usecase I have in mind for this.
