### ISSUE TITLE
improve wording in "simplified setup" dialog. 

### ISSUE THREAD

**Issue by hpk42** [deltachat/interface#33]
![simpl1](https://user-images.githubusercontent.com/73579/55278569-67585300-530e-11e9-9e64-9954d50c3661.png)

"login manually" would be better than "cancel" i think.   One never quite knows what "cancel" does -- it is easily interpreted as one of those "click-through" screens everybody grew accustomed with.

**Comment by r10s** [comment]
playing around with the change (i am currently playing around with a lot of log in stuff), i think this change is not really an improvement, i reasoned about it at https://github.com/deltachat/deltachat-android/pull/1231/commits/3d62b128b91207c82e994205674fd8a945489c82 and reverted the changed there.

feel free to reopen this issue if needed.
