### ISSUE TITLE
Backup & Restore UX

### ISSUE THREAD

**Issue by missytake** [deltachat/interface#35]
Hey, wrt backup & restore UX - I just tried this out with my partner and came upon some things which are not very intuitive. It just set up the desktop client the first time, so it exported a backup from the android app, transfered it to the Desktop via micro USB cable, and imported it into the fresh delta-desktop installation (xubuntu).

My partner looked for "import backup" in the settings, as it first tried to login, and then discovered "oh, my chats aren't there". That it had to logout and then find "import backup" on the login screen was not obvious at all. Maybe we should rethink it from this side?

Other people also ran into this already:
https://support.delta.chat/t/import-backup-only-at-new-install-no-import-menu-item-in-settings/445/2

Other improvements could be done (those have already mentioned a few times I think):
- Backups are automatically stored in the Download folder on Android, my partner expected to be able to choose a folder.
- When importing backups on Android, just the last one is taken from the Download folder.

**Comment by r10s** [comment]
i think, an attempt that would already improve things a lot would be to say on export, where you can import the thing.

**Comment by missytake** [comment]
Just for the record, found another topic on support.delta.chat about this: https://support.delta.chat/t/restore-backup-bak-on-android/900

**Comment by r10s** [comment]
i think, we can close this stale issue. the way to export/import is the mentioned "add second device", export/import stays as a "nerd" thing. i also assume, the time the issue was filed, the "import" option was far more hidden than it is nowadays.

**Comment by missytake** [comment]
> It is not completely clear what the issue is about, adding "Import backup" to "Advanced settings" on desktop so it is discoverable without going to account switcher?

Yes, this is what I was trying to suggest I think. But I'm fine with closing this for now.
