### ISSUE TITLE
Better name for "Contact requests"

### ISSUE THREAD

**Issue by testbird** [deltachat/interface#5]
**Not all** messages under "contact requests" really are requests to become a chat contact.

The wording "Contact Requests" contributes to the notion that the listed *emails* seem to be just a copy or listing of the local deltachat, and may be deleted to clean the messages that are not needed in deltachat.

The list shows the users last received emails on the server, which did not approve for chat and have not been moved into the DeltaChat folder (or possibly moved back).  It's actually a current part of the email INBOX.

Being able to delete some spam from within deltachat right away may be handy, but it should not be required at all, as the email INBOX is usually handled from within some other classic email client.
So the listing in deltachat can just get cleaned up by syncing (also deletes) with the server. 

For an improved wording we need to ask what is really shown (more precisely)?

There have been a lot of ideas (see below), the current version seems to be

**Incoming Emails**

---
Other ideas:
   ~~chats vs. e-mails
   chats vs. letters
   push notifications vs. browsing
   chat vs. non-chat messages~~

    approved vs. not approved email messages for chats

An improved wording could thus be "(...) Unapproved Emails" or better "(...) Unapproved New Emails", or just "(..) Incoming Emails".

---

If a reachability setting requires the user to actively follow the  "(...) Incoming Emails" in order to find out about actual contact requests by new, unknown contacts, it could be the default to show a small counter of "(...) unseen emails" right in the header of the chat list.

See https://support.delta.chat/t/make-contact-requests-more-visible/196
(While the button is present in the header of the chat list it could be removed from the menu.)

**Comment by testbird** [comment]
And what is the better name now?

**Comment by r10s** [comment]
seems as if this issue is controversial and stale and has no real outcome. seems as if no one wants to spend energy on it since more than a year, therefore i close it as our issues only reflects things someone is actually working on.
