### ISSUE TITLE
how much is "Password & Account" related to "Profile"?

### ISSUE THREAD

**Issue by r10s** [deltachat/interface#57]
all of android/ios/desktop already have roughly the same ordering in the settings and the same clickpaths, that's great - and already much better than things i've seen on other multi-platform apps ❤️

<img width=250 src=https://github.com/deltachat/interface/assets/9800740/63281c44-8c73-4a06-b3ed-81fc93a6750e>
<img width=250 src=https://github.com/deltachat/interface/assets/9800740/844ec2f0-6c45-42d8-a8c5-039a33541bc0>
<img width=280 src=https://github.com/deltachat/interface/assets/9800740/0cfdf2f9-833a-426f-b674-7e6ab9c020a8><br><br>

the main difference is that that "Password & Account" are _inside_ the "Profile" on android/ios  where on desktop _related_  to the "Profile" visually

but that relation was maybe more a copy thingie in the past, iirc, it was never really thought much about it :)

so questions that that pop up before we can proceed on improvements and unify [^1] [^2]

1. is "Password and Account" really related to "Profile"?

2. assuming a user using the upcoming instant-account: how important is "Password and Account" really?  is it worth a top-position? 

once we've better ideas about that, we can think about how to unify 

[^1]: there are [ideas on android](https://github.com/deltachat/deltachat-android/pull/2892) and [ideas on ios](https://github.com/deltachat/deltachat-ios/pull/2003) to move "Password & Account" out of profile as well, and there is a PR on [desktop to improve layout](https://github.com/deltachat/deltachat-desktop/pull/3575)

[^2]: there are obviously some side questions, but let's focus on that

**Comment by Simon-Laux** [comment]
I'd say if not top level, then it should be inside of advanced to be closer to the other imap settings.
But even for instant account is is an important item, because it is used to initiate AEAP and that's also an important part of the instant account effort: that you can migrate away from our server.

**Comment by r10s** [comment]
> I'd say if not top level, then it should be inside of advanced to be closer to the other imap settings.

+1
