### ISSUE TITLE
check statements about "No Servers"

### ISSUE THREAD

**Issue by Raiden-GH** [deltachat/interface#64]
I noticed the following statement in the new account screen:

> There are no Delta Chat servers, your data stays on your device.

Since the chatmail server started, this is no longer correct and could irritate new users.
One possibility would be to simply leave out the sentence or change it. 
For example: "_Delta Chat does not collect user data, everything stays on your device._"?

![New Account](https://github.com/deltachat/interface/assets/108235546/1054b1e0-be7c-466b-b2d0-32c18ae1c587)

**Comment by r10s** [comment]
thanks a lot for bringing that up! onboarding is about being revamped currently, see https://github.com/deltachat/deltachat-desktop/pull/3773, so we'll have a closer look at that 

> For example: "Delta Chat does not collect user data, everything stays on your device."?

good suggestion to leave that bit out and not force a discusssion

(one can probably nitpick how much chatmail is related to Delta Chat - now and in the future - however, we leave that to the experts :)
