### ISSUE TITLE
Formatting text (e.g. markdown)

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/interface#9]
It would be nice if all applications had similar functionality for writing/interpreting formatted text.

I propose the following:

* `*bold*` for **bold**
* `_italic_` for _italic_
* backtics for `code`

Anything else?

Maybe we could pick the same type of markdown style and just pass a message text through it to generate appropriate formatting, e.g. html for desktop (not sure what's appropriate in an android or iOS context)

**Comment by dignifiedquire** [comment]
if we do this, I would strongly argue for github flavored markdown, it is so engrained for many people and has shown that it works across a large community

**Comment by r10s** [comment]
ftr: meanwhile, this seems to be pretty stable documented, include source code snippets etc. at https://commonmark.org - github, reddit, stackoverflow subscribed to this spec.

**Comment by Simon-Laux** [comment]
discussion is on the forum now: https://support.delta.chat/t/markdown-support-in-chat/159

we would probably do the markdown via the message parser, so discussion about the spec should go to issues there or do a direct pr to change the spec document: https://github.com/deltachat/message-parser/blob/master/spec.md
